stages:
  - build
  - pre-test
  - correctness
  - test_mt
  - collect
  - test_lat
  - analysis

build:
  stage: build
  tags:
    - docker
    - exclusive
  script:
    - nice -n 19 make -j
  artifacts:
    untracked: true
    expire_in: 1 day

pre-test:
  stage: pre-test
  tags:
    - docker
    - exclusive
  script:
    - mkdir -p log/test_{mt,lat}
  artifacts:
    paths:
      - log/
    expire_in: 1 day

Fixsized-Write:
  stage: correctness
  tags:
    - docker
    - exclusive
  script:
    - nice -n 0 make test TEST_LOAD=1 TEST_ARGS='30 1 1 10 0 0' 2>&1

Try-test_mt:
  stage: correctness
  tags:
    - docker
    - exclusive
  script:
    - nice -n 0 make test_mt TEST_LOAD=1 TEST_ARGS='20 4 4 8 6 6' 2>&1

Try-test_lat:
  stage: correctness
  tags:
    - docker
    - exclusive
  script:
    - nice -n 0 make test_lat TEST_LOAD=1 TEST_ARGS="20 4 4 10 1 1" 2>&1

4K-Overlay:
  stage: test_mt
  tags:
    - docker
    - exclusive
  only:
    - benchmark
  script:
    - nice -n 0 make test_mt TEST_ARGS='24 4 4 15 8 10' 2>&1 | tee log/test_mt/4K-Overlay.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

4K-Discrete:
  stage: test_mt
  tags:
    - docker
    - exclusive
  only:
    - benchmark
  script:
    - nice -n 0 make test_mt TEST_ARGS='30 4 4 10 7 9' 2>&1 | tee log/test_mt/4K-Discrete.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

64K-Overlay:
  stage: test_mt
  tags:
    - docker
    - exclusive
  only:
    - benchmark
  script:
    - nice -n 0 make test_mt TEST_ARGS='25 64 64 14 9 11' 2>&1 | tee log/test_mt/64K-Overlay.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

64K-Discrete:
  stage: test_mt
  tags:
    - docker
    - exclusive
  only:
    - benchmark
  script:
    - nice -n 0 make test_mt TEST_ARGS='30 64 64 10 6 8' 2>&1 | tee log/test_mt/64K-Discrete.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

1M-Overlay:
  stage: test_mt
  tags:
    - docker
    - exclusive
  only:
    - benchmark
  script:
    - nice -n 0 make test_mt TEST_ARGS='26 1024 1024 10 5 7' 2>&1 | tee log/test_mt/1M-Overlay.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

1M-Discrete:
  stage: test_mt
  tags:
    - docker
    - exclusive
  only:
    - benchmark
  script:
    - nice -n 0 make test_mt TEST_ARGS='31 1024 1024 8 4 6' 2>&1 | tee log/test_mt/1M-Discrete.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

.collect:
  stage: collect
  tags:
    - docker
    - exclusive
  only:
    - benchmark
  script:
    - mkdir -p log/test_mt
  artifacts:
    paths:
      - log/

.latency:
  stage: test_lat
  tags:
    - docker
    - exclusive
  only:
    - benchmark
  script:
    - for k in `seq 2 12 | sed 's/\([0-9]*\)/2^\1/g' | bc`; do for l in `seq 0 6`; do nice -n 0 make test_lat TEST_LOAD=1 TEST_ARGS="31 $k $k 10 $l $l" 2>&1 | tee 'log/test_lat/latency-'$k'KB-'$l'Round.log'; done done 
  artifacts:
    paths:
      - log/
    expire_in: 1 day

analysis:
  stage: analysis
  tags:
    - docker
    - exclusive
  only:
    - benchmark
  script:
    - for i in `ls log/test_mt/*.log`; do echo $i; head -n11 $i | tail -n+2; grep iops $i | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t; echo; echo; done
    - for i in `ls log/test_lat/*.log`; do echo $i; head -n11 $i | tail -n+2; sed -n '/^[^,]*,[\.,0-9[:space:]]*$/p' $i | tee -a log/test_lat/summary.csv; echo; echo; done
  artifacts:
    paths:
      - log/
