stages:
  - build
  - pre-test
  - test_mt
  - test_lat
  - collect
  - analysis

build:
  stage: build
  script:
    - nice -n 19 make -j
  artifacts:
    untracked: true
    expire_in: 1 day

pre-test:
  stage: pre-test
  script:
    - mkdir -p log/test_{mt,lat}
  artifacts:
    paths:
      - log/
    expire_in: 1 day

4K-Overlay:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='24 4 4 17 8 10' 2>&1 | tee log/test_mt/4K-Overlay.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

4K-Discrete:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='30 4 4 13 8 10' 2>&1 | tee log/test_mt/4K-Discrete.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

64K-Overlay:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='26 64 64 14 8 10' 2>&1 | tee log/test_mt/64K-Overlay.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

64K-Discrete:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='30 64 64 10 6 8' 2>&1 | tee log/test_mt/64K-Discrete.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

1M-Overlay:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='26 1024 1024 10 5 7' 2>&1 | tee log/test_mt/1M-Overlay.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

1M-Discrete:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='31 1024 1024 9 4 6' 2>&1 | tee log/test_mt/1M-Discrete.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

4K-1IO-latency:
  stage: test_lat
  script:
      - nice -n 0 make test_lat TEST_ARGS='31 4 4 10 0 0' 2>&1 | tee log/test_lat/4K-1IO-latency.log
  artifacts:
    paths:
      - log/
    expire_in: 1 day

4K-8IOs-latency:
  stage: test_lat
  script:
      - nice -n 0 make test_lat TEST_ARGS='31 4 4 10 3 3' 2>&1 | tee log/test_lat/4K-8IOs-latency.log
  artifacts:
    paths:
      - log/
    expire_in: 1 day

4K-64IOs-latency:
  stage: test_lat
  script:
      - nice -n 0 make test_lat TEST_ARGS='31 4 4 10 6 6' 2>&1 | tee log/test_lat/4K-64IOs-latency.log
  artifacts:
    paths:
      - log/
    expire_in: 1 day

64K-1IO-latency:
  stage: test_lat
  script:
      - nice -n 0 make test_lat TEST_ARGS='31 64 64 10 0 0' 2>&1 | tee log/test_lat/64K-1IO-latency.log
  artifacts:
    paths:
      - log/
    expire_in: 1 day

64K-8IOs-latency:
  stage: test_lat
  script:
      - nice -n 0 make test_lat TEST_ARGS='31 64 64 10 3 3' 2>&1 | tee log/test_lat/64K-8IOs-latency.log
  artifacts:
    paths:
      - log/
    expire_in: 1 day

64K-64IOs-latency:
  stage: test_lat
  script:
      - nice -n 0 make test_lat TEST_ARGS='31 64 64 10 6 6' 2>&1 | tee log/test_lat/64K-64IOs-latency.log
  artifacts:
    paths:
      - log/
    expire_in: 1 day

1M-1IO-latency:
  stage: test_lat
  script:
      - nice -n 0 make test_lat TEST_ARGS='31 1024 1024 10 0 0' 2>&1 | tee log/test_lat/1M-1IO-latency.log
  artifacts:
    paths:
      - log/
    expire_in: 1 day

1M-8IOs-latency:
  stage: test_lat
  script:
      - nice -n 0 make test_lat TEST_ARGS='31 1024 1024 10 3 3' 2>&1 | tee log/test_lat/1M-8IOs-latency.log
  artifacts:
    paths:
      - log/
    expire_in: 1 day

1M-64IOs-latency:
  stage: test_lat
  script:
      - nice -n 0 make test_lat TEST_ARGS='31 1024 1024 10 6 6' 2>&1 | tee log/test_lat/1M-64IOs-latency.log
  artifacts:
    paths:
      - log/
    expire_in: 1 day

collect:
  stage: collect
  script:
      - tree log
  artifacts:
    paths:
      - log/

analysis:
  stage: analysis
  script:
    - for i in `ls log/test_mt/*.log`; do echo $i; head -n11 $i | tail -n+2; grep iops $i | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t; echo; echo; done
