stages:
  - build
  - test
  - analysis

build:
  stage: build
  script:
    - nice -n 19 make -j
  artifacts:
    untracked: true
    expire_in: 1 day

4K-Overlay:
  stage: test
  script:
    - mkdir -p log
    - nice -n 19 make test_mt TEST_ARGS='24 12 12 17 8 10' 2>&1 | tee log/4K-Overlay.log
    - head -n11 log/*.log | tail -n+2
    - grep iops log/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

4K-Discrete:
  stage: test
  script:
    - mkdir -p log
    - nice -n 19 make test_mt TEST_ARGS='30 12 12 13 8 10' 2>&1 | tee log/4K-Discrete.log
    - head -n11 log/*.log | tail -n+2
    - grep iops log/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

64K-Overlay:
  stage: test
  script:
    - mkdir -p log
    - nice -n 19 make test_mt TEST_ARGS='26 16 16 14 8 10' 2>&1 | tee log/64K-Overlay.log
    - head -n11 log/*.log | tail -n+2
    - grep iops log/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

64K-Discrete:
  stage: test
  script:
    - mkdir -p log
    - nice -n 19 make test_mt TEST_ARGS='30 16 16 10 6 8' 2>&1 | tee log/64K-Discrete.log
    - head -n11 log/*.log | tail -n+2
    - grep iops log/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

1M-Overlay:
  stage: test
  script:
    - mkdir -p log
    - nice -n 19 make test_mt TEST_ARGS='26 20 20 12 5 7' 2>&1 | tee log/1M-Overlay.log
    - head -n11 log/*.log | tail -n+2
    - grep iops log/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

1M-Discrete:
  stage: test
  script:
    - mkdir -p log
    - nice -n 19 make test_mt TEST_ARGS='31 20 20 9 4 6' 2>&1 | tee log/1M-Discrete.log
    - head -n11 log/*.log | tail -n+2
    - grep iops log/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

analysis:
  stage: analysis
  script:
    - for i in `ls log/*.log`; do echo $i; head -n11 $i | tail -n+2; grep iops $i | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t; echo; echo; done

