stages:
  - build
  - pre-test
  - test_lat
  - test_mt
  - analysis

build:
  stage: build
  script:
    - nice -n 19 make -j
  artifacts:
    untracked: true
    expire_in: 1 day

pre-test:
  stage: pre-test
  script:
    - mkdir -p log/test_{mt,lat}
  artifacts:
    paths:
      - log/
    expire_in: 1 day

4K-Overlay:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='24 4 4 17 8 10' 2>&1 | tee log/test_mt/4K-Overlay.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

4K-Discrete:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='30 4 4 13 8 10' 2>&1 | tee log/test_mt/4K-Discrete.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

64K-Overlay:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='26 64 64 14 8 10' 2>&1 | tee log/test_mt/64K-Overlay.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

64K-Discrete:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='30 64 64 10 6 8' 2>&1 | tee log/test_mt/64K-Discrete.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

1M-Overlay:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='26 1024 1024 10 5 7' 2>&1 | tee log/test_mt/1M-Overlay.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

1M-Discrete:
  stage: test_mt
  script:
    - nice -n 0 make test_mt TEST_ARGS='31 1024 1024 9 4 6' 2>&1 | tee log/test_mt/1M-Discrete.log
    - head -n11 log/test_mt/*.log | tail -n+2
    - grep iops log/test_mt/*.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t
  artifacts:
    paths:
      - log/
    expire_in: 1 day

latency:
  stage: test_lat
  script:
    - for k in `seq 2 12 | sed 's/\([0-9]*\)/2^\1/g' | bc`; do for l in `seq 0 6`; do nice -n 0 make test_lat TEST_LOAD=1 TEST_ARGS="31 $k $k 10 $l $l" 2>&1 | tee 'log/test_lat/latency-'$k'KB-'$l'Round.log' && head -n11 'log/test_lat/latency-'$k'KB-'$l'Round.log' | tail -n+2; done done 
  artifacts:
    paths:
      - log/
    expire_in: 1 day

analysis:
  stage: analysis
  script:
    - for i in `ls log/test_mt/*.log`; do echo $i; head -n11 $i | tail -n+2; grep iops $i | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t; echo; echo; done
    - for i in `ls log/test_lat/*.log`; do echo $i; head -n11 $i | tail -n+2; sed -n '/^[^,]*,[\.,0-9[:space:]]*$/p' $i | tee -a log/test_lat/summary.csv; echo; echo; done
  artifacts:
    paths:
      - log/
