stages:
  - build
  - test
  - analysis

build:
  stage: build
  script:
    - nice -n 19 make -j
  artifacts:
    untracked: true
    expire_in: 1 day

test_mt:
  stage: test
  script:
    - mkdir -p log
    - make test_mt 2>&1 | tee log/test_mt.log
  artifacts:
    paths:
      - log/
    expire_in: 1 day

analysis:
  stage: analysis
  script:
    - grep iops log/test_mt.log | sed 's/:.*, /:#/' | sed 's/#\([0-9][0-9]\.\)/# \1/' | column -s# -t

